### ISSUE TITLE
MAIN Failed to parse genesis block

### ISSUE THREAD

**Issue by Akash76** [hyperledger/iroha#1324]
![screenshot from 2018-05-09 21-33-22](https://user-images.githubusercontent.com/29705984/39825916-a53c36d4-53d0-11e8-87b9-221862db9510.png)
I have followed the guide lines that are provided in the git hub...but after giving command "irohad --config config.docker --genesis_block genesis.block --keypair_name node0", it is throwing error  "[th:17][error] MAIN Failed to parse genesis block"...

Expected output is to launch iroha daemon...

**Comment by laSinteZ** [comment]
@Akash76 could you send us previous commands you entered. Also, please, try to go through http://iroha.readthedocs.io/en/latest/getting_started/ once again (Don't forget to remove created containers with `docker rm`), maybe you mistyped some command :(

**Comment by Akash76** [comment]
i have removed all the old containers...and the commands are as stated in the getting started page...network name is iroha-network...user=postgres...password=mysecretpassword...just started that and trying to see iroha daemon.

**Comment by laSinteZ** [comment]
@Akash76 please provide screenshoots/logs of commands if possible so we can find the source of a problem :)

**Comment by laSinteZ** [comment]
@Akash76 I've found a source of a problem, we are investigating now and will fix it. Stay tuned!

**Comment by Akash76** [comment]
![screenshot from 2018-05-09 22-04-34](https://user-images.githubusercontent.com/29705984/39827243-04eef482-53d5-11e8-9aff-24a7baa8363a.png)
This is what i have done...same commands given in getting started

**Comment by laSinteZ** [comment]
@Akash76 we've made some changes to `develop` branch (adding new permission), but I think that our docker image hasn't updated yet. As a temporary workaround, please remove the 34 line in `iroha/example/genesis.block`
<img width="500" alt="screen shot 2018-05-09 at 19 40 23" src="https://user-images.githubusercontent.com/10958990/39827545-e5feea00-53c0-11e8-831d-3c6efcfb89f6.png"> like this :)

**Comment by Akash76** [comment]
it worked...but why is that having issue??

**Comment by Akash76** [comment]
Thank you @laSinteZ

**Comment by laSinteZ** [comment]
As I said, we have updated our `develop` branch (added new possible permission `can_get_blocks`), but not all of our docker images have updated right now. This why in docker image you have a bit older version of iroha, which knows nothing about new permission in genesis block and doesn't want to run. We will fix it soon (by updating docker images).

If you have time, please try running Iroha docker-container with `hyperledger/iroha:x86_64-develop` image, it should contain the newest version.

**Comment by Akash76** [comment]
Yeah sure...ill try that. Once again Thank you @laSinteZ

**Comment by laSinteZ** [comment]
I am closing this issue since problem is resolved and we will update our iroha:docker very soon.

**Comment by GaurManish** [comment]
[2019-01-03 06:44:17.632213751][th:10][info] IROHAD [Init] => storage
[2019-01-03 06:44:17.632780942][th:10][error] MAIN Failed to parse genesis block.

The same error any solution ??

**Comment by GaurManish** [comment]
![image](https://user-images.githubusercontent.com/39953298/50625945-52f3fc80-0f51-11e9-9292-df62fc2bf34a.png)

**Comment by GaurManish** [comment]
Please help me resolve this issue

**Comment by richhildyard** [comment]
Same problem. The image has been corrected to remove can_get_blocks from admin's permissions, but I am getting the same error as GaurManish. Any thoughts?

**Comment by darwinharianto** [comment]
tried to use the genesis block from dev branch at example>genesis.block, still have the same problem.

**Comment by Mingela** [comment]
@darwinharianto try `docker system prune -f` if it is convenient for you since it helped me once when an old block store format was conflicting with a new one or previously running containers was not shut down correctly

**Comment by darwinharianto** [comment]
> @darwinharianto try `docker system prune -f` if it is convenient for you since it helped me once when an old block store format was conflicting with a new one or previously running containers was not shut down correctly

tried `docker system prune -f` still have the same error report

**Comment by l4l** [comment]
@darwinharianto There was a release week ago, it's located on master branch. May I ask you for trying it out (with its genesis block)? That should be an outdated issue, since for now some useful logs (if the block is incorrect) should be printed as well.
